apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jsb-python-app
spec:
  ingressClassName: nginx
  rules:
  - host: jsb-python-app.test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jsb-python-app
            port:
              number: 8080